services:
  home-cinema-bridge:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.14.5"
    container_name: home-cinema-bridge
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      XNOPPO_CONFIG_FILE: /config/config.json
    volumes:
      - home-cinema-bridge-config:/config

volumes:
  home-cinema-bridge-config:
    name: home-cinema-bridge-config